prefixes = [
    "Shadow", "Iron", "Ghost", "Night", "Steel", "Storm", "Fire", "Frost", "Dragon", "Thunder",
    "Blood", "Stone", "Dark", "Silver", "Crystal", "Wind", "Dusk", "Ember", "Flame", "Grim",
    "Ice", "Lunar", "Mystic", "Phantom", "Razor", "Savage", "Silent", "Sky", "Solar", "Spirit",
    "Star", "Swift", "Valkyrie", "Venom", "Void", "Wolf", "Zephyr", "Arcane", "Ash", "Bane",
    "Beast", "Black", "Blaze", "Bright", "Chaos", "Claw", "Cold", "Cinder", "Dagger", "Death",
    "Deep", "Dire", "Dread", "Edge", "Eternal", "Fang", "Glory", "Hawk", "Hell", "Jade",
    "King", "Lion", "Lone", "Midnight", "Nova", "Pierce", "Rage", "Raven", "Reaper", "Smoke",
    "Soul", "Sun", "Talon", "Tide", "Tomb", "Toxic", "Venge", "Viper", "Wraith", "Zenith",
    "Zodiac", "Ashen", "Blight", "Brimstone", "Chrome", "Crimson", "Doom", "Echo",
    "Feral", "Frostbite", "Gale", "Gloom", "Grave", "Hallowed", "Icefang", "Ivory",
    "Jagged", "Keen", "Knight", "Lethal", "Magma", "Noble", "Obsidian", "Omen", "Pale",
    "Quake", "Radiant", "Rogue", "Rune", "Seeker", "Shade", "Shattered", "Skull",
    "Slayer", "Specter", "Spine", "Terror", "Twilight", "Umbral", "Vicious",
    "Wild", "Wrath", "Wretched", "Corrupted", "Darkened", "Deadly", "Desolate",
    "Enchanted", "Fierce", "Haunted", "Infernal", "Lost", "Malevolent", "Molten",
    "Piercing", "Raging", "Sinister", "Sorrow", "Spectral", "Spellbound", "Tempered",
    "Vengeful", "War", "Wicked", "Zealous", "Zeroth", "Abyssal", "Amber", "Aquila",
    "Berserk", "Celestial", "Cobalt", "Crag", "Cryptic", "Dawn", "Duskborn",
    "Ebon", "Emberglow", "Frostwind", "Gilded", "Gloomshade", "Harrow",
    "Ironclad", "Jadefire", "Kiln", "Luminous", "Moonlit", "Nether", "Onyx", "Pyre",
    "Quicksilver", "Runebound", "Sable", "Seismic", "Serrated", "Shard", "Silentfall",
    "Skyfire", "Smolder", "Snowdrift", "Solaris", "Stormborn", "Sunfire", "Tempest",
    "Thunderstrike", "Tundra", "Umber", "Voidborne", "Vortex", "Wildfire", "Winter",
    "Wither", "Zephyrwind", "Zodiacal", "Ardent", "Aurora", "Blazing", "Boulder",
    "Brumal", "Cinderfall", "Cloud", "Crimsonfire", "Dreadnought", "Eclipse", "Emberstorm",
    "Frostfang", "Galeheart", "Graveborn", "Iceveil", "Ironfang", "Jaggededge",
    "Knightfall", "Lurking", "Moonshadow", "Nighthawk", "Obsidianflame", "Phantomshade",
    "Quartz", "Ravenwing", "Runic", "Shadowflame", "Silverwind", "Stormwatch", "Thorn",
    "Thunderclap", "Tidebreaker", "Twilightfall", "Voidwalker", "Windshear", 
    "Alex", "Ben", "Cara", "Dylan", "Ella", "Finn", "Grace", "Hannah", "Ian", "Jade",
    "Kai", "Liam", "Mia", "Nina", "Owen", "Piper", "Quinn", "Rory", "Sage", "Tara",
    "Uma", "Vera", "Will", "Xander", "Yara", "Zane", "Adam", "Bella", "Caleb", "Daisy",
    "Eli", "Fiona", "Gavin", "Hazel", "Isaac", "Jenna", "Kara", "Leo", "Maya", "Noah",
    "Olivia", "Paige", "Reed", "Sara", "Theo", "Violet", "Wyatt", "Zoe", "Aaron", "Bria",
    "Cody", "Daphne", "Evan", "Faith", "Gabe", "Hailey", "Ivan", "June", "Kris", "Lara",
    "Mark", "Nora", "Omar", "Penny", "Quincy", "Rhea", "Sean", "Tess", "Uri", "Val",
    "Wade", "Yasmin", "Zack", "Amber", "Blake", "Cora", "Derek", "Erin", "Felix", "Gina",
    "Holden", "Ivy", "Jack", "Kylie", "Landon", "Molly", "Nate", "Opal", "Paul", "Rose",
    "Rylan", "Sienna", "Trent", "Una", "Vince", "Willa", "Xena", "Yosef", "Zara", "Asher",
    "Brooke", "Colin", "Diana", "Eliot", "Freya", "Glen", "Hope", "Jesse", "Kara", "Luke",
    "Mila", "Nash", "Olive", "Parker", "Reese", "Shay", "Toby", "Ursula", "Vance", "Wren",
    "Xavi", "Yvette", "Zion", "Alina", "Brady", "Casey", "Dana", "Eden", "Frank", "Gia",
    "Harry", "Isla", "Jude", "Kira", "Lila", "Miles", "Nina", "Owen", "Pia", "Quinn",
    "Rex", "Seth", "Tia", "Vera", "West", "Yanni", "Zeke", "Aidan", "Brielle", "Craig",
    "Delia", "Ezra", "Faye", "Gage", "Holly", "Ira", "Jillian", "Kian", "Leah", "Mason",
    "Nyla", "Orion", "Paula", "Rhys", "Sky", "Tyler", "Ulysses", "Vivian", "Wesley",
    "Ximena", "Yolanda", "Zander"
]

middles = [
    "Slayer", "Sniper", "Blade", "Knight", "Hunter", "Rogue", "Warden", "Nomad", "Ranger", "Scout",
    "Archer", "Berserker", "Duelist", "Lancer", "Gladiator", "Corsair", "Privateer", "Brigand", "Bandit", "Paladin",
    "Templar", "Crusader", "Warlock", "Sorcerer", "Wizard", "Enchanter", "Pyromancer", "Juggernaut", "Colossus", "Titan",
    "Behemoth", "Leviathan", "Kraken", "Wyrm", "Drake", "Serpent", "Centurion", "Marshal", "Captain", "Admiral",
    "Harbinger", "Herald", "Envoy", "Emissary", "Messenger", "Trickster", "Jester", "Harrier", "Huntsman", "Pathfinder",
    "Pioneer", "Outrider", "Rider", "Cavalier", "Dragoon", "Skirmisher", "Watcher", "Guardian", "Defender", "Protector",
    "Bulwark", "Shield", "Hammer", "Fist", "Fang", "Claw", "Maul", "Axe", "Spear", "Bow",
    "Arrow", "Bolt", "Blast", "Charge", "Rush", "Strike", "Smite", "Slash", "Pierce", "Sting",
    "Bite", "Roar", "Howl", "Growl", "Snarl", "Tracker", "Packleader", "Alpha", "Scoutmaster", "Watchman",
    "Lookout", "Sentry", "Seafarer", "Mariner", "Voyager", "Navigator", "Seeker", "Sentinel",
    "Vanguard", "Marauder", "Reaver", "Brawler", "Prowler", "Cutter", "Striker", "Marksman", "Champion", "Keeper",
    "Rune", "Glyph", "Sigil", "Spell", "Hex", "Curse", "Charm", "Blessing", "Altar", "Ritual",
    "Shrine", "Totem", "Relic", "Artifact", "Talisman", "Amulet", "Ring", "Crown", "Throne", "Banner",
    "Emblem", "Badge", "Insignia", "Mystic", "Oracle", "Beast", "Wolf", "Tiger", "Bear", "Lion",
    "Panther", "Jaguar", "Cobra", "Viper", "Wyvern", "Basilisk", "Hydra", "Manticore", "Golem", "Elemental",
    "Sprite", "Imp", "Demon", "Angel", "Djinn", "Nymph", "Dryad", "Specter", "Revenant", "Zombie",
    "Skeleton", "Ghoul", "Lich", "Kappa", "Griffin", "Phoenix", "Roc", "Sword", "Dagger", "Rapier",
    "Cutlass", "Sabre", "Mace", "Flail", "Pike", "Halberd", "Lance", "Crossbow", "Shot", "Thrust",
    "Jab", "Stab", "Chop", "Cleave", "Crush", "Bash", "Whirl", "Spin", "Sprint", "Leap",
    "Vault", "Dash", "Ambush", "Snipe", "Ambusher", "Cleric", "Priest", "Bard", "Minstrel", "Chronicler",
    "Archivist", "Scribe", "Cartographer", "Beacon", "Light", "Night", "Dawn", "Dusk", "Sun", "Moon", "Star", "Tide", "Wave", "Ocean", "Reef", "Sand", "Dust", "Earth", "Stone", "Rock",
    "Cliff", "Peak", "Vale", "Grove", "Thorn", "Ice", "Frost", "Flame", "Ember", "Blaze",
    "Ash", "Smoke", "Gale", "Wind", "Breeze", "Zephyr", "Thunder", "Lightning", "Rain", "Snow",
    "Hail", "Mist", "Fog", "Cloud", "Sky", "Solar", "Lunar", "Tempest", "Tundra", "Umber",
    "Void", "James", "Marie", "Lee", "Ann", "John", "Grace", "Ray", "Lou", "Paul", "Jane",
    "Mark", "Elle", "Jean", "Kai", "Beth", "Rey", "Rae", "Dean", "Jay", "May",
    "Dale", "Nell", "Clara", "Jude", "Mae", "Noel", "Tate", "Eve", "Quinn", "Ruth",
    "Lynn", "Beau", "Hope", "Gail", "Wade", "Blair", "Jace", "Skye", "Lane", "Drew",
    "Reed", "Cade", "Rex", "Vance", "Saul", "Eli", "Asa", "Faye", "Zane", "Lux",
    "Troy", "Shay", "Seth", "Hale", "Finn", "Joss", "Kirk", "Milo", "Owen", "Zeke",
    "Tess", "Paige", "Dean", "Glenn", "Holly", "Jill", "Kaye", "Lee", "Lark", "Neal",
    "Perry", "Rory", "Sage", "Tina", "Vera", "Wynn", "Zara", "Alex", "Blake", "Chase",
    "Dane", "Ellis", "Frank", "Gale", "Haze", "Ira", "Jack", "Kane", "Lane", "Mace",
    "Nate", "Olin", "Pax", "Rey", "Sean", "Tate", "Vail", "Wade", "Zion", "Abel",
    "Blaine", "Casey", "Drew", "Evan", "Flynn", "Grant", "Hayes", "Ivy", "Jude", "Kirk",
    "Luca", "Mila", "Noah", "Owen", "Paige", "Quinn", "Reese", "Shane", "Tara", "Vince",
    "Wren", "Xane", "Yara", "Zane", "Amos", "Beck", "Cruz", "Dale", "Eli", "Finn",
    "Gray", "Hale", "Ivan", "Joss", "Kade", "Lyle", "Mace", "Nico", "Omar", "Pax",
    "Reed", "Seth", "Troy", "Vale", "Wynn", "Zeke", "Asa", "Beau", "Cal", "Dane",
    "Ellis", "Gage", "Holt", "Jace", "Kane", "Leif", "Milo", "Nash", "Oren", "Pierce",
    "Rex", "Saul", "Tate", "Vail", "West", "Zion", "Ari", "Bryn", "Cade", "Drew",
    "Evan", "Fox", "Gray", "Hale", "Ira", "Jett", "Kirk", "Lane", "Milo", "Nash",
    "Odin", "Pax", "Reed", "Seth", "Tate", "Vail", "Wynn", "Zane"
]

suffixes = [
    "123", "x", "xx", "zzz", "guy", "gal", "pro", "player", "gamer", "hd", "jr", "sr",
    "boss", "king", "queen", "god", "noob", "legend", "champ", "killer", "sniper", "shot",
    "fire", "ice", "blade", "wolf", "hawk", "fox", "bear", "dragon", "shadow", "ghost",
    "ninja", "samurai", "viper", "cobra", "wolfy", "beast", "killer", "sniper", "strike",
    "rush", "shot", "dash", "speed", "flash", "boom", "blast", "storm", "stormy",
    "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
    "xoxo", "luv", "life", "fire", "ice", "light", "dark", "warrior", "fighter", "hunter",
    "rocket", "rocketman", "rocketgirl", "smash", "crush", "bang", "buzz", "pop", "snap",
    "zoom", "kingpin", "queenbee", "alpha", "omega", "max", "mini", "mega", "super", "ultra",
    "mega", "baby", "cool", "rad", "lit", "dope", "fresh", "wild", "mad", "crazy",
    "fast", "quick", "sharp", "slick", "smooth", "loud", "heavy", "bold", "brave", "keen",
    "dark", "light", "red", "blue", "green", "black", "white", "gold", "silver", "bronze",
    "steel", "iron", "chrome", "neon", "urban", "retro", "classic", "modern", "prime", "neo",
    "meta", "cyber", "tech", "ghost", "shadow", "phantom", "mystic", "legend", "champ",
    "ace", "rookie", "veteran", "master", "boss", "king", "queen", "duke", "baron", "sir",
    "lady", "captain", "commander", "chief", "spark", "pulse", "beat", "flow", "wave",
    "gear", "zone", "quest", "path", "trail", "step", "move", "spin", "roll", "crash",
    "blast", "kick", "jump", "fly", "run", "climb", "slide", "burst", "flash", "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
    "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson",
    "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores",
    "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts",
    "Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker", "Cruz", "Edwards", "Collins", "Reyes",
    "Stewart", "Morris", "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper",
    "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson",
    "Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes",
    "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long", "Ross", "Foster", "Jimenez",
    "Powell", "Jenkins", "Perry", "Russell", "Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes",
    "Gonzales", "Fisher", "Vasquez", "Simmons", "Romero", "Jordan", "Patterson", "Alexander", "Hamilton", "Graham",
    "Reynolds", "Griffin", "Wallace", "Moreno", "West", "Cole", "Hayes", "Bryant", "Herrera", "Gibson",
    "Ellis", "Tran", "Medina", "Aguilar", "Stevens", "Murray", "Ford", "Castro", "Marshall", "Owens",
    "Harrison", "Fernandez", "Mcdonald", "Woods", "Washington", "Kennedy", "Wells", "Vargas", "Henry", "Chen",
    "Freeman", "Webb", "Tucker", "Guzman", "Burns", "Crawford", "Olson", "Simpson", "Porter", "Hunter",
    "Gordon", "Mendez", "Silva", "Shaw", "Snyder", "Mason", "Dixon", "Munoz", "Hunt", "Hicks",
    "Holmes", "Palmer", "Wagner", "Black", "Robertson", "Boyd", "Rose", "Stone", "Salazar", "Fox",
    "Warren", "Mills", "Meyer", "Rice", "Schmidt", "Garza", "Daniels", "Ferguson", "Nichols", "Stephens",
    "Soto", "Weaver", "Ryan", "Gardner", "Payne", "Grant", "Dunn", "Kelley", "Spencer", "Hawkins"
]